language: java
jdk:
- openjdk10
- openjdk11
script:
- "./gradlew test"
- "./gradlew build"
- "./gradlew uberJar"

before_deploy: "mv build/libs/gocd-google-chat-build-notifier-uber.jar build/libs/gocd-google-chat-build-notifier-plugin.jar"

deploy:
  provider: releases
  api_key:
    secure: "MgsQkCcWEdsuNHS7LMGWj49taaJ30fy9yfbJhDYE5ME0pwwR7ssaxK5Aq0M1rbAl78S+axSEW9Gc6smcQ+AUAcURmPYOnJN7S/hsb7uWqgiZlM/OvvVn4lUDoXzroQP+73JsgfrOxfbipqBgWj8D/GKbEo3oGHVQO/L4HjP93Lw36GMlvt8VUMhOTmx8RaPgSr2nVIilKcuLj7kr4fMsZF7MfwOVMXcISRcqi/oPA+CImxvcGJZbP+y5NA4eNrxk9KftQTHPg5A+LS2OrRmLqkAByLZ1UZbKWYpqs2DB78+Sy11OlMWcUG6Dz4lV2lTPR14gZYGe0uSi1NTkapUNsMQm78PWJlxgaBj4wrXoavcznITZAcE14Ld7Y1r8jn6NhaXMXEG29RVvWlzDXjPb1O1TOYUlTJPut7QRJqksTujCYX0LjIFRi8OxSoQyzmkaO0RTH6QR1bDMAgRDOOehoVbZJqgRbwm7XffMCr2Bw+4K1lhMjzRv/8ucUAdMXP+EAaiqzpzKfHuRok92cg3lW2BDIeBXWcQueMlTFQbxa/lUrrB9T06IDY7xOCl2W9cgf8mhouBVkmlqBsid6fsXrcrBaHF//fPqxhSYlTiIMd2XOJU5ErcNvLN8jQeD2fq7gayo+8r1utj4KupieNgKLLmJyhWDcpxIdEdk//jB1bY="
  file: build/libs/gocd-google-chat-build-notifier-plugin.jar
  on:
    tags: true
